info:
  contact: {}
  description: This is a sample server.
  title: GoChat API
  version: "1.0"
paths:
  /admin/createUser:
    get:
      description: create user
      parameters:
      - description: 用户名 6-20位
        in: query
        name: name
        required: true
        type: string
      - description: 密码 6-20位
        in: query
        name: password
        required: true
        type: string
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      - description: 邮箱
        in: query
        name: email
        type: string
      responses:
        "200":
          description: user list是用户名列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 错误信息
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      tags:
      - Admin
  /admin/deleteUserByID:
    get:
      description: delete user
      parameters:
      - description: 用户ID
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Delete user success
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 错误信息
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      tags:
      - Admin
  /admin/getUserByID:
    get:
      description: get userinfo by id
      parameters:
      - description: 用户ID
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: user list是用户名列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 错误信息
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      tags:
      - Admin
  /admin/getUserList:
    get:
      description: get userlist
      responses:
        "200":
          description: user list是用户列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 错误信息
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      tags:
      - Admin
  /admin/updateUser:
    post:
      description: update user
      parameters:
      - description: 用户ID
        in: query
        name: id
        required: true
        type: integer
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      - description: 手机号
        in: query
        name: phone
        type: string
      - description: 邮箱
        in: query
        name: email
        type: string
      - description: 身份
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: Update user success
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 错误信息
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      tags:
      - Admin
  /index:
    get:
      consumes:
      - application/json
      description: get index
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - test
  /login:
    post:
      description: user login
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: Login success
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 错误信息
          schema:
            additionalProperties: true
            type: object
      tags:
      - User
  /ping:
    get:
      consumes:
      - application/json
      description: ping test
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - test
  /register:
    post:
      description: register user
      parameters:
      - description: 用户名 6-20位
        in: query
        name: name
        required: true
        type: string
      - description: 密码 6-20位
        in: query
        name: password
        required: true
        type: string
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      - description: 邮箱
        in: query
        name: email
        type: string
      responses:
        "200":
          description: user list是用户名列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 错误信息
          schema:
            additionalProperties: true
            type: object
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
