info:
  contact: {}
paths:
  /index:
    get:
      consumes:
      - application/json
      description: get index
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /ping:
    get:
      consumes:
      - application/json
      description: ping test
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Ping
  /user/createUser:
    get:
      description: create user
      parameters:
      - description: 用户名 6-20位
        in: query
        name: name
        required: true
        type: string
      - description: 密码 6-20位
        in: query
        name: password
        required: true
        type: string
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      - description: 邮箱
        in: query
        name: email
        type: string
      responses:
        "200":
          description: user list是用户名列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 错误信息
          schema:
            additionalProperties: true
            type: object
      tags:
      - UserInfo
  /user/deleteUserByID:
    get:
      description: delete user
      parameters:
      - description: 用户ID
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Delete user success
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 错误信息
          schema:
            additionalProperties: true
            type: object
      tags:
      - UserInfo
  /user/getUserByID:
    get:
      description: get userinfo by id
      parameters:
      - description: 用户ID
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: user list是用户名列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 错误信息
          schema:
            additionalProperties: true
            type: object
      tags:
      - UserInfo
  /user/getUserList:
    get:
      description: get userlist
      responses:
        "200":
          description: user list是用户列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 错误信息
          schema:
            additionalProperties: true
            type: object
      tags:
      - UserInfo
  /user/login:
    post:
      description: user login
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: Login success
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 错误信息
          schema:
            additionalProperties: true
            type: object
      tags:
      - UserInfo
  /user/updateUser:
    post:
      description: update user
      parameters:
      - description: 用户ID
        in: query
        name: id
        required: true
        type: integer
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      - description: 手机号
        in: query
        name: phone
        type: string
      - description: 邮箱
        in: query
        name: email
        type: string
      - description: 身份
        in: query
        name: identity
        type: string
      responses:
        "500":
          description: 错误信息
          schema:
            additionalProperties: true
            type: object
      tags:
      - UserInfo
swagger: "2.0"
